model:
  type: 'vla'
  policy_list: ['pi0.5', 'smolvla']
  policy: 'smolvla'          # pi0.5 | smolvla
  #checkpoint: '/workspace/m.ax/checkpoints/a6000_260416/pi05_kitting_scratch_a6000_b16_260413/checkpoints/034000/pretrained_model'
  checkpoint: '/workspace/m.ax/checkpoints/local_260410/smolvla_kitting_scratch_b32/checkpoints/082000/pretrained_model'
  task_prompt: 'pick part and flip part'
  device: 'cuda'            # cuda | cpu
  dtype: 'bfloat16'         # float32 | bfloat16

data_collect:
  type: 'lerobot'
  task_prompt: 'flip object'
  hz: 30
  warmup_sec: 1.0
  img_shape: '640x480'
  output_dir: '/workspace/m.ax/datasets'
  repo_id: 'kitting_dataset'

env:
  robot:
    type: 'fr3'
    ip: '172.16.0.2'
    comm: 'ros2'
    topic:
      ros_domain_id: 0
      subscribe: 
        /joint_states:
          type: sensor_msgs/JointState
          hz: 30
        /franka_robot_state_broadcaster/current_pose:
          type: geometry_msgs/msg/PoseStamped
          hz: 30
        /franka_robot_state_broadcaster/external_joint_torques:
          type: sensor_msgs/msg/JointState
          hz: 30
      publish: 
        /gello/joint_states:
          type: sensor_msgs/JointState
          hz: 30
    joint_list:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    pose:
      home:  # joint space
        - 0.878352701663971
        - 0.3663146495819092
        - 0.20556820929050446
        - -1.6565794944763184
        - -0.06079482287168503
        - 2.0056283473968506
        - 1.8882989883422852
      kit:  # joint space
        - -0.22613531351089478
        - -0.052150316536426544
        - 0.3750353157520294
        - -1.90276300907135
        - 0.03822034224867821
        - 1.83684504032135
        - 2.5277857780456543

  gripper:
    type: 'dxl_parallel_gripper'
    comm: 'ros2'
    topic:
      ros_domain_id: 0
      subscribe: 
        /dxl_parallel_gripper/joint_states: 
          type: 'sensor_msgs/JointState'
          hz: 30
      publish: 
        /gripper/gripper_client/target_gripper_width_percent:
          type: 'std_msgs/Float32'
          hz: 30
    joint_list:
      - finger_joint
    pose:
      open:
        - 1.0
      close:
        - 0.0
  camera:
    camera_1:
      comm: 'ros2'
      type: 'realsense'
      model: 'd405'      
      name: 'wrist_front'
      topic:
        ros_domain_id: 1
        subscribe:
          /wrist/front/color/image_raw/compressed:
            type: 'sensor_msgs/msg/CompressedImage'
            hz: 30
      port: ''
      serial: ''
      size: [848, 480]
      rotate: 0
    camera_2:
      comm: 'ros2'
      type: 'realsense'
      model: 'd405'
      name: 'wrist_rear'
      topic:
        ros_domain_id: 1
        subscribe:
          /wrist/rear/color/image_raw/compressed:
            type: 'sensor_msgs/msg/CompressedImage'
            hz: 30
      port: /dev/video1
      serial: ''
      size: [848, 480]
      rotate: 180
    camera_3:
      comm: 'ros2'
      type: 'orbbec'
      model: 'gemini2'
      name: 'front_view'
      topic:
        ros_domain_id: 1
        subscribe:
          /front_view/color/image_raw/compressed:
            type: 'sensor_msgs/msg/CompressedImage'
            hz: 30
      port: ''
      serial: ''
      size: [1280, 720]
      rotate: 0
    camera_4:
      comm: 'ros2'
      type: 'orbbec'
      model: 'gemini2'
      name: 'side_view'
      topic:
        ros_domain_id: 1
        subscribe:
          /side_view/color/image_raw/compressed:
            type: 'sensor_msgs/msg/CompressedImage'
            hz: 30
      port: ''
      serial: ''
      size: [1280, 720]
      rotate: 0

