inference:
  fps: 30
  default_policy:
    framework: lerobot
    policy: smolvla
    checkpoint: /workspace/m.ax/checkpoints/local_260410/smolvla_kitting_scratch_b32/checkpoints/082000/pretrained_model
    device: cuda
    dtype: bfloat16
  default_task_instruction: "pick part and flip part"
  default_expression_type: rot6d

robot:
  type: fr3
  joint_list:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  subscribe:
    - topic: /joint_states
      type: sensor_msgs/msg/JointState
      role: joint_states
    - topic: /franka_robot_state_broadcaster/current_pose
      type: geometry_msgs/msg/PoseStamped
      role: current_pose
  publish:
    - topic: /gello/joint_states
      type: sensor_msgs/msg/JointState
      role: joint_command

gripper:
  subscribe:
    - topic: /dxl_parallel_gripper/joint_states
      type: sensor_msgs/msg/JointState
      role: gripper_state
  publish:
    - topic: /gripper/gripper_client/target_gripper_width_percent
      type: std_msgs/msg/Float32
      role: gripper_command

cameras:
  - name: wrist_front
    topic: /wrist/front/color/image_raw/compressed
    type: sensor_msgs/msg/CompressedImage
    rotate: 0
  - name: wrist_rear
    topic: /wrist/rear/color/image_raw/compressed
    type: sensor_msgs/msg/CompressedImage
    rotate: 180
  - name: front_view
    topic: /front_view/color/image_raw/compressed
    type: sensor_msgs/msg/CompressedImage
    rotate: 0
  - name: side_view
    topic: /side_view/color/image_raw/compressed
    type: sensor_msgs/msg/CompressedImage
    rotate: 0
